### ISSUE TITLE
jplugins/coremgt - Malformed version error

### ISSUE THREAD

**Issue by ldouillet** [forj-oss/jplugins#51] opened 2021-05-20 19:40 UTC
jplugins is returning an error when using the version format proposed for the [JEP-229](https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc). 

For exemple when adding in the `jplugins.lst` the [plugin:azure-credentials](https://github.com/jenkinsci/azure-credentials-plugin/releases) which latest version is `182.v3ccd4a755864`  results in the below error:

```
[2021-05-18T00:01:44.606Z] ERROR ! jplugins/coremgt.(*pluginsStatusDetails).initFromRef: New version
'182.v3ccd4a755864' invalid. Malformed version: 182.v3ccd4a755864
[2021-05-18T00:01:44.606Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-05-18T00:01:44.606Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x6f98e7]
[2021-05-18T00:01:44.606Z] goroutine 1 [running]:
[2021-05-18T00:01:44.606Z] jplugins/coremgt.(*PluginsStatus).addPlugin(0xc4213e7eb8, 0x0, 0x0, 0x0, 0xc4202535e0, 0xc4213e7b00)
[2021-05-18T00:01:44.606Z] 	/go/src/jplugins/coremgt/plugins-status.go:283 +0x117
[2021-05-18T00:01:44.606Z] jplugins/coremgt.(*PluginsStatus).CheckPlugin(0xc4213e7eb8, 0xc422989a87, 0x11, 0x0, 0x0, 0x0, 0xc422989a87, 0x11)
[2021-05-18T00:01:44.606Z] 	/go/src/jplugins/coremgt/plugins-status.go:517 +0x2b5
[2021-05-18T00:01:44.606Z] main.(*jPluginsApp).readFeatures.func1(0xc422989a80, 0x6, 0xc422989a87, 0x11, 0x0, 0x0)
[2021-05-18T00:01:44.606Z] 	/go/src/jplugins/jplugins-app.go:125 +0x2c4
```

**Comment by clarsonneur** [comment] 2021-05-20 20:49
Hi,

I think the version string is probably the root cause of this core dump.

I will check this, how to manage this use case in the code.

**Comment by clarsonneur** [comment] 2021-05-20 21:02
This is something related to the module `github.com/hashicorp/go-version`

This module do not support this string as a version.
I have to check this plugin version as sample of this issue which break down jplugins. jplugins needs to sort versions.
With such string, it can be tricky.

I'll do some test to guide on this.

**Comment by clarsonneur** [comment] 2021-05-24 19:51
I think, the only option we have here is to create a parallel version. Normal version as managed by go-version and a simple version check based on string order.

I'm designing this.

Could you tell me which version of the tool you are using, guys?
0.0.9 or latest?

**Comment by ldouillet** [comment] 2021-05-25 11:31
@clarsonneur , for now `0.0.9`

**Comment by clarsonneur** [comment] 2021-05-25 21:44
ok. I think I found a good approach to fix it.

I was not sure if in 182.v3ccd4a755864 we can ignore everything after the dot for goversion module. but it works.
goversion follow the Semver convention.
and if we eliminate some part of the string which do not respect the Semver, then it looks definitely better.

I made some try with exotic versions, and it seems that my latest fix do MAKE it !

I'm pushing it as latest. You could get it and make a try.

**Comment by clarsonneur** [comment] 2021-05-25 21:59
latest release is updated.

get it and check the version string.
it should be :
`jplugins pre-release V1.0.0-10 - 2021-05-25_23:46:56_+0200 - 78d25bbb40bd81717d2781f1cacd62443ae1d3bb`

Tell me and enjoy!

**Comment by clarsonneur** [comment] 2021-05-26 12:31
As soon as resolution confirmed, I will create a dedicated release to permit a stable download link.

**Comment by clarsonneur** [comment] 2021-06-08 20:26
I guess, all is good. I will create a final version in coming days.

Closing for now.

**Closed by clarsonneur** 2021-06-08 20:26 UTC
Labels: Waiting for feedback, bug
